defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  run:
    dir: ./baseline_rerun/${env_name}_seed=${seed}
  sweep:
    dir: ./baseline_rerun/${env_name}_seed=${seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
  launcher:
    partition: learnlab
    gpus_per_task: 1
    mem_gb: 15
    timeout_min: 800

save_dir: ./models/checkpoint.pt
load_dir: null
log_dir: ./logs
algo: idaac
seed: 0

env_name: coinrun
start_level: 0
num_levels: 200
distribution_mode: easy
num_env_steps: 25e6
num_processes: 64

use_best_hps: true
lr: 5e-4
eps: 1e-5
hidden_size: 256
log_interval: 10
clip_param: 0.2
num_mini_batch: 8
ppo_epoch: 3
num_steps: 256
max_grad_norm: 0.5
value_loss_coef: 0.5
entropy_coef: 0.01
gae_lambda: 0.95
gamma: 0.999
alpha: 0.99
no_cuda: false

clf_hidden_size: 4
order_loss_coef: 0.001
use_nonlinear_clf: false

adv_loss_coef: 0.25
value_freq: 1
value_epoch: 9
