defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: random
  - override hydra/launcher: submitit_slurm

hydra:
  sweeper: 
    sampler:
      seed: ${seed}
    direction: minimize
    study_name: rs-${env_name}-s${seed}
    n_trials: 16
    n_jobs: 100
    params: 
      batch_size: choice(128,256,512,1024,2048)
      num_minibatches: range(0,7)
      num_update_epochs: range(1,15)
      reward_scaling: interval(0.01, 1.0)
      entropy_cost: interval(0.0001, 0.5)
      learning_rate: interval(0.00001, 0.001)
      gae_lambda: interval(0.5, 0.999)
      epsilon: interval(0.01, 0.9)
      vf_coef: interval(0.01, 0.9)
  run:
    dir: tuning_results_rs/${env_name}_${seed}
  launcher:
    partition: learnfair
    mem_gb: 40
    gpus_per_task: 1
    timeout_min: 1720
  sweep:
    dir: tuning_results_rs/${env_name}_${seed}

tuning_seeds: [0,1,2,3,4]
env_name: ant
episode_length: 1000
num_timesteps: 30000000
unroll_length: 5
batch_size: 1024
num_minibatches: 6
num_update_epochs: 4
reward_scaling: 0.1
entropy_cost: 1e-2
learning_rate: 3e-4
gae_lambda: 0.95
epsilon: 0.3
vf_coef: 0.5
outdir: '.'
seed: 0
save: 'checkpoint.pt'
load: null
use_cuda: false


