agent_class: DQN
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: CnnPolicy
model_kwargs:
  learning_rate: 0.007385279051959518
  batch_size: 4
  tau: 1.0
  gamma: 0.999
  learning_starts: 8535
  train_freq: 709
  gradient_steps: 3
  exploration_fraction: 0.3867299258708954
  exploration_initial_eps: 0.9006227254867554
  exploration_final_eps: 0.05258572474122048
  buffer_size: 18708046