agent_class: DQN
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: CnnPolicy
model_kwargs:
  learning_rate: 1.0535660074893417e-05
  batch_size: 8
  tau: 1.0
  gamma: 0.999
  learning_starts: 853
  train_freq: 72
  gradient_steps: 6
  exploration_fraction: 0.20811840357066505
  exploration_initial_eps: 0.8407972945631884
  exploration_final_eps: 0.04596267748614324
  buffer_size: 45895936