agent_class: DQN
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: CnnPolicy
model_kwargs:
  learning_rate: 1.0010585318259673e-05
  batch_size: 16
  tau: 1.0
  gamma: 0.999
  learning_starts: 157
  train_freq: 114
  gradient_steps: 9
  exploration_fraction: 0.268976944244543
  exploration_initial_eps: 0.6451186309002647
  exploration_final_eps: 0.12142554420541403
  buffer_size: 29047741