agent_class: DQN
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: CnnPolicy
model_kwargs:
  learning_rate: 1.4177841275181747e-05
  batch_size: 8
  tau: 1.0
  gamma: 0.999
  learning_starts: 100
  train_freq: 4
  gradient_steps: 1
  exploration_fraction: 0.3410035743325868
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.05
  buffer_size: 1000000