agent_class: DQN
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: CnnPolicy
model_kwargs:
  learning_rate: 1.277057593458669e-05
  batch_size: 4
  tau: 1.0
  gamma: 0.999
  learning_starts: 12
  train_freq: 531
  gradient_steps: 2
  exploration_fraction: 0.21261859377647213
  exploration_initial_eps: 0.8364022971130278
  exploration_final_eps: 0.14745600000000003
  buffer_size: 32000000