agent_class: DQN
total_timesteps: 1000000.0
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 0.00015450018247892784
  batch_size: 64
  tau: 1.0
  gamma: 0.9
  learning_starts: 50000
  train_freq: 4
  gradient_steps: 1
  exploration_fraction: 0.1
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.05
  buffer_size: 1000000