agent_class: DQN
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: CnnPolicy
model_kwargs:
  learning_rate: 1.3394542251066526e-06
  batch_size: 4
  tau: 1.0
  gamma: 0.999
  learning_starts: 6829
  train_freq: 14
  gradient_steps: 7
  exploration_fraction: 0.03847468865159697
  exploration_initial_eps: 0.5455457653337659
  exploration_final_eps: 0.1553265846159871
  buffer_size: 954485