agent_class: DQN
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: CnnPolicy
model_kwargs:
  learning_rate: 1.003127986346439e-06
  batch_size: 8
  tau: 1.0
  gamma: 0.999
  learning_starts: 3435
  train_freq: 21
  gradient_steps: 7
  exploration_fraction: 0.3281317863924571
  exploration_initial_eps: 0.5024591292606321
  exploration_final_eps: 0.0023098711684505736
  buffer_size: 30495273