agent_class: PPO
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
num_minibatches: 8
model_kwargs:
  learning_rate: 0.0005489921383559711
  batch_size: 128
  gamma: 0.9
  n_steps: 2048
  n_epochs: 5
  gae_lambda: 0.8
  clip_range: 0.5
  clip_range_vf: 0.35631446167280345
  normalize_advantage: True
  ent_coef: 0.1329462432861328
  vf_coef: 0.2688882107147704
  max_grad_norm: 0.5535405349731446
  use_sde: False
  sde_sample_freq: 4