agent_class: PPO
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
num_minibatches: 8
model_kwargs:
  learning_rate: 1.2697111322756417e-06
  batch_size: 64
  gamma: 0.9
  n_steps: 1024
  n_epochs: 10
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: True
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: False
  sde_sample_freq: 4