agent_class: SAC
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 0.008016442648861638
  batch_size: 128
  tau: 0.2328039597914336
  gamma: 0.99
  learning_starts: 5579
  buffer_size: 18081430
  train_freq: 654
  gradient_steps: 1
  use_sde: False
  sde_sample_freq: -1