agent_class: SAC
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 1.178063047424396e-05
  batch_size: 256
  tau: 0.32609808160673476
  gamma: 0.99
  learning_starts: 100
  buffer_size: 1000000
  train_freq: 158
  gradient_steps: 1
  use_sde: False
  sde_sample_freq: -1