agent_class: SAC
total_timesteps: 25e6
n_eval_episodes: 5
policy_model: CnnPolicy
model_kwargs:
  learning_rate: 5e-4
  batch_size: 64
  tau: 1.0
  gamma: 0.999
  learning_starts: 100
  buffer_size: 1000000
  train_freq: 1
  gradient_steps: 1
  use_sde: False
  sde_sample_freq: -1