agent_class: SAC
total_timesteps: 1000000.0
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 2.8772916926549774e-06
  batch_size: 64
  tau: 0.6209734644845166
  gamma: 0.99
  learning_starts: 5737
  buffer_size: 148502
  train_freq: 904
  gradient_steps: 3
  use_sde: false
  sde_sample_freq: -1