agent_class: SAC
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 0.00015676677195506063
  batch_size: 256
  tau: 0.6067357423109274
  gamma: 0.99
  learning_starts: 100
  buffer_size: 1000000
  train_freq: 716
  gradient_steps: 1
  use_sde: False
  sde_sample_freq: -1