agent_class: SAC
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 0.000981469638645649
  batch_size: 64
  tau: 0.14575493335723877
  gamma: 0.99
  learning_starts: 7139
  buffer_size: 117145
  train_freq: 59
  gradient_steps: 1
  use_sde: False
  sde_sample_freq: -1