agent_class: SAC
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 0.00021416058974333633
  batch_size: 128
  tau: 0.12164845308569075
  gamma: 0.99
  learning_starts: 5510
  buffer_size: 48645670
  train_freq: 351
  gradient_steps: 5
  use_sde: False
  sde_sample_freq: -1