agent_class: SAC
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 0.001468588598920087
  batch_size: 256
  tau: 0.8713120267643509
  gamma: 0.99
  learning_starts: 8327
  buffer_size: 38908947
  train_freq: 21
  gradient_steps: 1
  use_sde: False
  sde_sample_freq: -1