agent_class: SAC
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 0.007820313796401024
  batch_size: 128
  tau: 0.3407002389431
  gamma: 0.99
  learning_starts: 7803
  buffer_size: 2260574
  train_freq: 582
  gradient_steps: 9
  use_sde: False
  sde_sample_freq: -1