agent_class: SAC
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 0.007316768410325889
  batch_size: 256
  tau: 0.18214376115421918
  gamma: 0.99
  learning_starts: 100
  buffer_size: 1000000
  train_freq: 18
  gradient_steps: 1
  use_sde: False
  sde_sample_freq: -1