agent_class: SAC
total_timesteps: 1e6
n_eval_episodes: 5
policy_model: MlpPolicy
model_kwargs:
  learning_rate: 0.0008040406272640493
  batch_size: 128
  tau: 0.2044167709331355
  gamma: 0.99
  learning_starts: 3660
  buffer_size: 27644464
  train_freq: 634
  gradient_steps: 10
  use_sde: False
  sde_sample_freq: -1