defaults:
  - algorithm: ppo
  - search_space: ppo
  - override hydra/sweeper: PBT
  - override hydra/launcher: submitit_slurm

hydra:
  sweeper: 
    budget: ${algorithm.total_timesteps}
    budget_variable: algorithm.total_timesteps
    loading_variable: load
    saving_variable: save
    optimizer: pb2
    pbt_kwargs:
      population_size: 10
      num_config_changes: 20
      categorical_mutation: mix
      wandb_project: autorl-benchmarks
      seeds: false
    search_space: ${search_space}
  run:
    dir: tuning_output_rebuttal/pb2_seed_${seed}_${algorithm.agent_class}_${env_name}_seeds_False
  launcher:
    partition: learnfair
    mem_gb: 10
    timeout_min: 1720
  sweep:
    dir: tuning_output_rebuttal/pb2_seed_${seed}_${algorithm.agent_class}_${env_name}_seeds_False

log_dir: ./agent_logs
env_name: Pendulum-v1
load: false
save: false
reward_curves: false
seed: 0
wandb: false
wandb_tags: [base]
logging_interval: 1e5