hyperparameters:
  algorithm.model_kwargs.learning_rate:
    type: uniform_float
    lower: 0.000001
    upper: 0.01
    log: true
  algorithm.model_kwargs.exploration_fraction:
    type: uniform_float
    lower: 0.005
    upper: 0.5
    log: false
  algorithm.model_kwargs.batch_size:
    type: categorical
    choices: [4, 8, 16, 32]