algorithm.model_kwargs.learning_rate: tag(log, interval(0.000001, 0.01))
algorithm.model_kwargs.exploration_fraction: interval(0.005, 0.5)
algorithm.model_kwargs.batch_size: choice(4, 8, 16, 32)
algorithm.model_kwargs.gradient_steps: range(1, 10)
algorithm.model_kwargs.train_freq: range(1, 1e3)
algorithm.model_kwargs.learning_starts: range(1, 1e4)
algorithm.model_kwargs.buffer_size: range(5e3, 5e7)
algorithm.model_kwargs.exploration_initial_eps: interval(0.5, 1.0)
algorithm.model_kwargs.exploration_final_eps: interval(0.001,0.2)