algorithm.model_kwargs.learning_rate: tag(log, interval(0.000001, 0.01))
algorithm.model_kwargs.batch_size: choice(16, 32, 64, 128)
algorithm.model_kwargs.n_steps: choice(256, 512, 1024, 2048, 4096)
algorithm.model_kwargs.n_epochs: range(5, 20)
algorithm.model_kwargs.gae_lambda: interval(0.8, 0.9999)
algorithm.model_kwargs.clip_range: interval(0.0, 0.5)
algorithm.model_kwargs.clip_range_vf: interval(0.0, 0.5)
algorithm.model_kwargs.normalize_advantage: choice(True, False)
algorithm.model_kwargs.ent_coef: interval(0.0, 0.5)
algorithm.model_kwargs.vf_coef: interval(0.0, 1.0)
algorithm.model_kwargs.max_grad_norm: interval(0.0, 1.0)