hyperparameters:
  algorithm.model_kwargs.learning_rate:
    type: uniform_float
    lower: 0.000001
    upper: 0.01
    log: true
  algorithm.model_kwargs.tau:
    type: uniform_float
    lower: 0.01
    upper: 1.0
    log: false
  algorithm.model_kwargs.train_freq:
    type: uniform_int
    lower: 1
    upper: 1e3
    log: false